<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FraudDetection.Core\FraudDetection.Core.csproj" />
    <ProjectReference Include="..\FraudDetection.ML\FraudDetection.ML.csproj" />
  </ItemGroup>

</Project>
